### ISSUE TITLE
環境構築

### ISSUE THREAD

**Issue by Mizukiiii5** [Mizukiiii5/Poetry_docker#1]
### ファイル構成

```
try-poetry-on-docker/
  ├ Dockerfile
  ├ docker-compose.yaml
  └ フォルダ/
    └ ファイル
```

### Dockerfile

```
FROM python:3.10

RUN apt-get update &&\
    apt-get -y install locales &&\
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ JST-9
ENV TERM xterm

RUN pip install --upgrade pip

# Poetryのインストール
RUN curl -sSL https://install.python-poetry.org | python -

# Poetryのパスの設定
ENV PATH /root/.local/bin:$PATH

# Poetryが仮想環境を生成しないようにする
RUN poetry config virtualenvs.create false
```

### docker-compose

```
version: '3'
services:
  poetrytest:
    restart: always
    build: .
    container_name: 'pandas'
    working_dir: '/root/フォルダ'
    tty: true
    volumes:
      - ./test:/root/フォルダ
```

### docker-compose description
version : Docker のバージョンを指定
services : Docker のコンテナ情報　name : poetrytest
container_name : コンテナの名前を指定
working_dir : コンテナ内に入った直後の作業ディレクトリを指定
volumes : ローカルに存在するディレクトリとコンテナ内のディレクトリを同期
ここでは、ローカルに設置したtestディレクトリが、コンテナ内のroot/testディレクトリと同期される。

### Dockerコンテナの起動

```
docker-compose up -d --build
```
### 停止
```
docker-compose down
```

### コンテナに入る
```
docker-compose exec poetrytest bash
```

### poetryの詳細設定
https://qiita.com/ksato9700/items/b893cf1db83605898d8a
